packages:
  - 'packages/*'

auditLevel: 'high'
blockExoticSubdeps: true
minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
nodeLinker: 'isolated'
preferFrozenLockfile: true
preferOffline: false
resolvePeersFromWorkspaceRoot: true
strictPeerDependencies: true
trustPolicy: 'no-downgrade'

allowBuilds:
  lefthook: false

catalog:
  # Tooling
  lefthook: '^2.1.14'
  oxfmt: '^0.68.0'
  oxlint: '^1.83.0'
  typescript: '^7.0.2'
