auditLevel: 'high'
blockExoticSubdeps: true
minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
nodeLinker: 'isolated'
preferFrozenLockfile: true
preferOffline: false
resolvePeersFromWorkspaceRoot: true
strictPeerDependencies: true
trustPolicy: 'no-downgrade'

catalog:
  # Tooling
  oxfmt: '^0.68.0'
  oxlint: '^1.83.0'
