#!/usr/bin/env bash
# Verifies that commit messages are a single line of <type>: <message>,
# where <type> is a Conventional Commits type, e.g. chore: set up repository
#
# As a commit-msg hook, git passes the path of the message file as the first
# argument. Comment lines and everything below the scissors line (added by
# `git commit -v`) are ignored, as git strips them from the final message.

set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/commit-types.sh"
PATTERN="^(${COMMIT_TYPES}): [^[:space:]](.*[^.[:space:]])?$"
MAX_LENGTH=100
# Messages generated by git itself (merges, reverts, autosquash)
GENERATED_PATTERN='^(Merge |Revert "|fixup! |squash! |amend! )'
SCISSORS='# ------------------------ >8 ------------------------'
BLANK_PATTERN='^[[:space:]]*$'

message_file="${1:?Usage: $0 <commit message file>}"

lines=()
while IFS= read -r line || [[ -n "${line}" ]]; do
  [[ "${line}" == "${SCISSORS}" ]] && break
  [[ "${line}" == \#* ]] && continue
  [[ "${line}" =~ ${BLANK_PATTERN} ]] && continue
  lines+=("${line}")
done < "${message_file}"

# An empty message is rejected by git itself
((${#lines[@]} == 0)) && exit 0

subject="${lines[0]}"

[[ "${subject}" =~ ${GENERATED_PATTERN} ]] && exit 0

errors=()
if ((${#lines[@]} > 1)); then
  errors+=("Commit message must be a single line, without body or footers")
fi
if [[ ! "${subject}" =~ ${PATTERN} ]]; then
  errors+=("Invalid commit message: \"${subject}\"")
fi
if ((${#subject} > MAX_LENGTH)); then
  errors+=("Commit message is ${#subject} characters long, max is ${MAX_LENGTH}")
fi

if ((${#errors[@]} > 0)); then
  for error in "${errors[@]}"; do
    echo "${error}" >&2
  done
  echo "Expected: <type>: <message> without trailing period, e.g. chore: set up repository" >&2
  echo "Allowed types: ${COMMIT_TYPES//|/, }" >&2
  exit 1
fi
